os: Visual Studio 2015

platform: x64

install:
    - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
    - appveyor-retry choco install strawberryperl --allow-empty-checksums
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - appveyor-retry git clone https://github.com/rakudo/rakudo.git %APPVEYOR_BUILD_FOLDER%\..\rakudo
    - cd %APPVEYOR_BUILD_FOLDER%\..\rakudo
    - perl Configure.pl --gen-moar --gen-nqp
    - nmake install
    - SET PATH=%APPVEYOR_BUILD_FOLDER%\..\rakudo\install\bin;%PATH%
    - SET PATH=%APPVEYOR_BUILD_FOLDER%\..\rakudo\install\share\perl6\site\bin;%PATH%
    - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
    - prove --ext .rakutest -v -e "raku -I." t/

shallow_clone: true
